//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFC___StandBy_CSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PFC___StandBy_CSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _894798_200 {
            get {
                object obj = ResourceManager.GetObject("894798-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _894798_2001 {
            get {
                object obj = ResourceManager.GetObject("894798-2001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _959ad3842394161b09d4cd3987c3f51c {
            get {
                object obj = ResourceManager.GetObject("959ad3842394161b09d4cd3987c3f51c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap acessorios_512px {
            get {
                object obj = ResourceManager.GetObject("acessorios_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap acessoriosl_52px {
            get {
                object obj = ResourceManager.GetObject("acessoriosl_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap address_20px {
            get {
                object obj = ResourceManager.GetObject("address_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Alcatel_Logo {
            get {
                object obj = ResourceManager.GetObject("Alcatel-Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap asus {
            get {
                object obj = ResourceManager.GetObject("asus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bg_ordensServicos {
            get {
                object obj = ResourceManager.GetObject("bg_ordensServicos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap birthday_cake_20px {
            get {
                object obj = ResourceManager.GetObject("birthday_cake_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage business_dollar {
            get {
                object obj = ResourceManager.GetObject("business_dollar", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage card_green {
            get {
                object obj = ResourceManager.GetObject("card green", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abadia
        ///Abadia de Carbonita
        ///Abadia de Goiás
        ///Abadia dos Dourados
        ///Abadiânia
        ///Abaeté
        ///Abaeté dos Mendes
        ///Abaeté dos Venâncios
        ///Abaetetuba
        ///Abaiara
        ///Abaíba
        ///Abaíra
        ///Abapã
        ///Abaré
        ///Abarracamento
        ///Abatiá
        ///Abdon Batista
        ///Abel Figueiredo
        ///Abelardo Luz
        ///Abílio Martins
        ///Abóbora
        ///Abraão
        ///Abrantes
        ///Abre Campo
        ///Abreu e Lima
        ///Abreulândia
        ///Abreus
        ///Abunã
        ///Acaiaca
        ///Açailândia
        ///Acajutiba
        ///Acará
        ///Acarape
        ///Acaraú
        ///Acari
        ///Acauã
        ///Acauã de Minas
        ///Aceguá
        ///Acioli
        ///Açoita Cavalo
        ///Acopiara
        ///Acorizal
        ///Acrelândia
        ///Acreúna
        ///Açu
        ///Açu da Torre
        ///Açuanópolis
        ///Açucena
        ///Açude dos Pinheir [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Cidades {
            get {
                return ResourceManager.GetString("Cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap city_20px {
            get {
                object obj = ResourceManager.GetObject("city_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap electrical_20px {
            get {
                object obj = ResourceManager.GetObject("electrical_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap family_20px {
            get {
                object obj = ResourceManager.GetObject("family_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fundo_editar_clientes {
            get {
                object obj = ResourceManager.GetObject("fundo editar clientes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google_banner {
            get {
                object obj = ResourceManager.GetObject("google banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google_banner_sem_fundo {
            get {
                object obj = ResourceManager.GetObject("google banner sem fundo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google_minimal_logo {
            get {
                object obj = ResourceManager.GetObject("google-minimal-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_add_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_add_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_add_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_add_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_android_20px_3 {
            get {
                object obj = ResourceManager.GetObject("icons8_android_20px_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_bulleted_list_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_bulleted_list_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_cancel_25px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_cancel_25px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_card_payment_20px_2 {
            get {
                object obj = ResourceManager.GetObject("icons8_card_payment_20px_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_checked_checkbox_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_checked_checkbox_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_checked_checkbox_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_checked_checkbox_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_checked_checkbox_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_checked_checkbox_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_checkmark_yes_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_checkmark_yes_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_comments_20px {
            get {
                object obj = ResourceManager.GetObject("icons8_comments_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_edit_account_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_edit_account_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_edit_file_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_edit_file_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_edit_file_512px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_edit_file_512px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_error_20px {
            get {
                object obj = ResourceManager.GetObject("icons8_error_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_estimate_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_estimate_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_list_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_list_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_money_bag_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_money_bag_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_notepad_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_notepad_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_ok_45px {
            get {
                object obj = ResourceManager.GetObject("icons8_ok_45px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_paint_roller_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_paint_roller_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_password_20px {
            get {
                object obj = ResourceManager.GetObject("icons8_password_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_phone_20px {
            get {
                object obj = ResourceManager.GetObject("icons8_phone_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_print_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_print_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_print_512px {
            get {
                object obj = ResourceManager.GetObject("icons8_print_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_reset_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_reset_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_reset_480px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_reset_480px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_search_208px {
            get {
                object obj = ResourceManager.GetObject("icons8_search_208px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_search_500px {
            get {
                object obj = ResourceManager.GetObject("icons8_search_500px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_shutdown_96px {
            get {
                object obj = ResourceManager.GetObject("icons8_shutdown_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_tick_box_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_tick_box_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_user_20px {
            get {
                object obj = ResourceManager.GetObject("icons8_user_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_user_group_480px {
            get {
                object obj = ResourceManager.GetObject("icons8_user_group_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap identification_documents_20px {
            get {
                object obj = ResourceManager.GetObject("identification_documents_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iPhone_logo {
            get {
                object obj = ResourceManager.GetObject("iPhone-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lenovo {
            get {
                object obj = ResourceManager.GetObject("lenovo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lglogo {
            get {
                object obj = ResourceManager.GetObject("lglogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LUCROS {
            get {
                object obj = ResourceManager.GetObject("LUCROS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap map_pin_20px {
            get {
                object obj = ResourceManager.GetObject("map_pin_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap motorola {
            get {
                object obj = ResourceManager.GetObject("motorola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ORCAMENTOS {
            get {
                object obj = ResourceManager.GetObject("ORCAMENTOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap phone_20px {
            get {
                object obj = ResourceManager.GetObject("phone_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap residence_20px {
            get {
                object obj = ResourceManager.GetObject("residence_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap road_20px {
            get {
                object obj = ResourceManager.GetObject("road_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap samsung_logo_png_samsung_logo_png_2104 {
            get {
                object obj = ResourceManager.GetObject("samsung-logo-png-samsung-logo-png-2104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap separador {
            get {
                object obj = ResourceManager.GetObject("separador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SERVICOS_COMPLETOS {
            get {
                object obj = ResourceManager.GetObject("SERVICOS_COMPLETOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings_480px {
            get {
                object obj = ResourceManager.GetObject("settings_480px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skyscrapers_20px {
            get {
                object obj = ResourceManager.GetObject("skyscrapers_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sms_20px {
            get {
                object obj = ResourceManager.GetObject("sms_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sucesso {
            get {
                object obj = ResourceManager.GetObject("Sucesso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        public static DevExpress.Utils.Svg.SvgImage task {
            get {
                object obj = ResourceManager.GetObject("task", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TITULO_CADASTRO_CLIENTES {
            get {
                object obj = ResourceManager.GetObject("TITULO_CADASTRO_CLIENTES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TITULO_ORDENS_DE_SERVICO {
            get {
                object obj = ResourceManager.GetObject("TITULO_ORDENS_DE_SERVICO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TITULO_STANDBY_SYSTEM {
            get {
                object obj = ResourceManager.GetObject("TITULO STANDBY SYSTEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toilet_20px {
            get {
                object obj = ResourceManager.GetObject("toilet_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap xiaomi1 {
            get {
                object obj = ResourceManager.GetObject("xiaomi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
