// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFC___StandBy_CSharp.Models
{
    public partial class tb_clientes
    {
        [Key]
        public int cl_id { get; set; }
        [Required]
        [StringLength(100)]
        public string cl_nome { get; set; }
        [Required]
        [StringLength(15)]
        public string cl_telefone { get; set; }
        [Required]
        [StringLength(18)]
        public string cl_cpf { get; set; }
        [Required]
        [StringLength(100)]
        public string cl_telefone_recado { get; set; }
        [StringLength(100)]
        public string cl_nome_recado { get; set; }
        [StringLength(50)]
        public string cl_parentesco_recado { get; set; }
        [StringLength(1)]
        public string cl_sexo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cl_data_nascimento { get; set; }
        [StringLength(10)]
        public string cl_cep { get; set; }
        [StringLength(200)]
        public string cl_endereco { get; set; }
        [StringLength(100)]
        public string cl_complemento { get; set; }
        [StringLength(50)]
        public string cl_bairro { get; set; }
        [StringLength(50)]
        public string cl_cidade { get; set; }
        [StringLength(50)]
        public string cl_estado { get; set; }
    }
}