// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFC___StandBy_CSharp.Models
{
    public partial class tb_comp_items
    {
       
        [Key]
        public int item_id { get; set; }
        [Required]
        [StringLength(50)]
        public string item_tela { get; set; }
        [Required]
        [StringLength(50)]
        public string item_grupo { get; set; }
        [StringLength(50)]
        public string item_nome { get; set; }
        public bool item_editavel { get; set; }
        [Required]
        [StringLength(50)]
        public string item_texto { get; set; }
    }
}