// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFC___StandBy_CSharp.Models
{
    public partial class tb_compras
    {
        [Key]
        public int cp_id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime cp_data { get; set; }
        public int cp_sv_id { get; set; }
        [Required]
        [StringLength(500)]
        public string cp_peca_comprada { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal cp_valor_peca { get; set; }
        [Required]
        [StringLength(200)]
        public string cp_fornecedor { get; set; }

        [ForeignKey(nameof(cp_sv_id))]
        [InverseProperty(nameof(tb_servicos.tb_compras))]
        public virtual tb_servicos cp_sv_ { get; set; }
    }
}