// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFC___StandBy_CSharp.Models
{
    public partial class tb_pagamento
    {
        [Key]
        public int pag_id { get; set; }
        public int pag_sv_id { get; set; }
        [Required]
        [StringLength(100)]
        public string pag_forma { get; set; }
        public int pag_parcelas { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal pag_valor { get; set; }

        [ForeignKey(nameof(pag_sv_id))]
        [InverseProperty(nameof(tb_servicos.tb_pagamento))]
        public virtual tb_servicos pag_sv_ { get; set; }
    }
}