// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFC___StandBy_CSharp.Models
{
    public partial class tb_servicos
    {
        public tb_servicos()
        {
            tb_checklist = new HashSet<tb_checklist>();
            tb_compras = new HashSet<tb_compras>();
            tb_condicoes_fisicas = new HashSet<tb_condicoes_fisicas>();
            tb_pagamento = new HashSet<tb_pagamento>();
        }

        [Key]
        public int sv_id { get; set; }
        public int sv_ordem_serv { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime sv_data { get; set; }
        public int sv_cl_idcliente { get; set; }
        [StringLength(50)]
        public string sv_tipo_aparelho { get; set; }
        [StringLength(50)]
        public string sv_marca { get; set; }
        [Required]
        [StringLength(50)]
        public string sv_aparelho { get; set; }
        [StringLength(50)]
        public string sv_cor { get; set; }
        [StringLength(50)]
        public string sv_mei_serialnumber { get; set; }
        [StringLength(300)]
        public string sv_defeito { get; set; }
        [StringLength(300)]
        public string sv_servico { get; set; }
        [StringLength(100)]
        public string sv_senha { get; set; }
        [StringLength(8000)]
        public string sv_situacao { get; set; }
        [StringLength(8000)]
        public string sv_acessorios { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? sv_valorservico { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? sv_valorpeca { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? sv_lucro { get; set; }
        public int? sv_status { get; set; }
        public int sv_ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? sv_data_conclusao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? sv_previsao_entrega { get; set; }
        public int? sv_existe_um_prazo { get; set; }
        [Column(TypeName = "image")]
        public byte[] sv_senha_pattern { get; set; }
        public int? sv_cor_tempo { get; set; }
        [StringLength(10)]
        public string sv_tempo_para_entregar { get; set; }
        [StringLength(8000)]
        public string sv_relato_cliente { get; set; }
        [StringLength(5000)]
        public string sv_condicoes_balcao { get; set; }
        [StringLength(20)]
        public string sv_avaliacao_servico { get; set; }

        [ForeignKey(nameof(sv_cl_idcliente))]
        [InverseProperty(nameof(tb_clientes.tb_servicos))]
        public virtual tb_clientes sv_cl_idclienteNavigation { get; set; }
        [InverseProperty("ch_sv_idservicoNavigation")]
        public virtual ICollection<tb_checklist> tb_checklist { get; set; }
        [InverseProperty("cp_sv_")]
        public virtual ICollection<tb_compras> tb_compras { get; set; }
        [InverseProperty("cf_sv_idservicoNavigation")]
        public virtual ICollection<tb_condicoes_fisicas> tb_condicoes_fisicas { get; set; }
        [InverseProperty("pag_sv_")]
        public virtual ICollection<tb_pagamento> tb_pagamento { get; set; }
    }
}