// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PFC___StandBy_CSharp.Models;

namespace PFC___StandBy_CSharp.Context
{
    public partial class standby_orgContext : DbContext
    {
        public standby_orgContext()
        {
        }

        public standby_orgContext(DbContextOptions<standby_orgContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tb_clientes> tb_clientes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-7MQSE1Q\\SQLEXPRESS;Initial Catalog=standby_org;User ID=sa;Password=123adr");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tb_clientes>(entity =>
            {
                entity.HasKey(e => e.cl_id)
                    .HasName("pk_tb_clientes");

                entity.Property(e => e.cl_bairro).IsUnicode(false);

                entity.Property(e => e.cl_cep).IsUnicode(false);

                entity.Property(e => e.cl_cidade).IsUnicode(false);

                entity.Property(e => e.cl_complemento).IsUnicode(false);

                entity.Property(e => e.cl_cpf)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('SEM CPF')");

                entity.Property(e => e.cl_endereco).IsUnicode(false);

                entity.Property(e => e.cl_estado).IsUnicode(false);

                entity.Property(e => e.cl_nome).IsUnicode(false);

                entity.Property(e => e.cl_nome_recado).IsUnicode(false);

                entity.Property(e => e.cl_parentesco_recado).IsUnicode(false);

                entity.Property(e => e.cl_sexo)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.cl_telefone)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('------------')");

                entity.Property(e => e.cl_telefone_recado)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('------------')");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}